author: Josh Kenzer
email: jkenzer@gmail.com
url: https://jkenzer.github.io/sketchbook/
description: > # this means to ignore newlines until "show_excerpts:"
  Sketchbook of p5.js projects
baseurl: /sketchbook
theme: jekyll-theme-merlot
#remote_theme: huangyz0918/moving
